import { Api } from '@/models/api'

export function getCountryByName(name: string): Api.CountryType {
    const countryMap = new Map([
        // Americas
        ['argentina', Api.CountryType.ARGENTINA],
        ['bahamas', Api.CountryType.BAHAMAS],
        ['barbados', Api.CountryType.BARBADOS],
        ['belize', Api.CountryType.BELIZE],
        ['bermuda', Api.CountryType.BERMUDA],
        ['bolivia', Api.CountryType.BOLIVIA],
        ['brazil', Api.CountryType.BRAZIL],
        ['canada', Api.CountryType.CANADA],
        ['cayman islands', Api.CountryType.CAYMAN_ISLANDS],
        ['chile', Api.CountryType.CHILE],
        ['colombia', Api.CountryType.COLOMBIA],
        ['costa rica', Api.CountryType.COSTA_RICA],
        ['cuba', Api.CountryType.CUBA],
        ['dominica', Api.CountryType.DOMINICA],
        ['dominican republic', Api.CountryType.DOMINICAN_REPUBLIC],
        ['ecuador', Api.CountryType.ECUADOR],
        ['el salvador', Api.CountryType.EL_SALVADOR],
        ['falkland islands', Api.CountryType.FALKLAND_ISLANDS],
        ['grenada', Api.CountryType.GRENADA],
        ['greenland', Api.CountryType.GREENLAND],
        ['guatemala', Api.CountryType.GUATEMALA],
        ['guyana', Api.CountryType.GUYANA],
        ['haiti', Api.CountryType.HAITI],
        ['honduras', Api.CountryType.HONDURAS],
        ['jamaica', Api.CountryType.JAMAICA],
        ['mexico', Api.CountryType.MEXICO],
        ['nicaragua', Api.CountryType.NICARAGUA],
        ['panama', Api.CountryType.PANAMA],
        ['paraguay', Api.CountryType.PARAGUAY],
        ['peru', Api.CountryType.PERU],
        ['puerto rico', Api.CountryType.PUERTO_RICO],
        ['saint kitts and nevis', Api.CountryType.SAINT_KITTS_AND_NEVIS],
        ['saint lucia', Api.CountryType.SAINT_LUCIA],
        ['saint vincent and the grenadines', Api.CountryType.SAINT_VINCENT_AND_THE_GRENADINES],
        ['suriname', Api.CountryType.SURINAME],
        ['trinidad and tobago', Api.CountryType.TRINIDAD_AND_TOBAGO],
        ['united states', Api.CountryType.UNITED_STATES],
        ['uruguay', Api.CountryType.URUGUAY],
        ['venezuela', Api.CountryType.VENEZUELA],
        ['virgin islands british', Api.CountryType.VIRGIN_ISLANDS_BRITISH],
        ['virgin islands us', Api.CountryType.VIRGIN_ISLANDS_US],

        // Asia Pacific
        ['australia', Api.CountryType.AUSTRALIA],
        ['bangladesh', Api.CountryType.BANGLADESH],
        ['bhutan', Api.CountryType.BHUTAN],
        ['brunei darussalam', Api.CountryType.BRUNEI_DARUSSALAM],
        ['cambodia', Api.CountryType.CAMBODIA],
        ['china', Api.CountryType.CHINA],
        ['christmas island', Api.CountryType.CHRISTMAS_ISLAND],
        ['cocos islands', Api.CountryType.COCOS_ISLANDS],
        ['fiji', Api.CountryType.FIJI],
        ['hong kong', Api.CountryType.HONG_KONG],
        ['india', Api.CountryType.INDIA],
        ['indonesia', Api.CountryType.INDONESIA],
        ['japan', Api.CountryType.JAPAN],
        ['kazakhstan', Api.CountryType.KAZAKHSTAN],
        ['kiribati', Api.CountryType.KIRIBATI],
        ['laos', Api.CountryType.LAOS],
        ['macau', Api.CountryType.MACAU],
        ['malaysia', Api.CountryType.MALAYSIA],
        ['maldives', Api.CountryType.MALDIVES],
        ['marshall islands', Api.CountryType.MARSHALL_ISLANDS],
        ['micronesia', Api.CountryType.MICRONESIA],
        ['mongolia', Api.CountryType.MONGOLIA],
        ['myanmar', Api.CountryType.MYANMAR],
        ['nepal', Api.CountryType.NEPAL],
        ['new caledonia', Api.CountryType.NEW_CALEDONIA],
        ['new zealand', Api.CountryType.NEW_ZEALAND],
        ['niue', Api.CountryType.NIUE],
        ['north korea', Api.CountryType.NORTH_KOREA],
        ['northern mariana islands', Api.CountryType.NORTHERN_MARIANA_ISLANDS],
        ['palau', Api.CountryType.PALAU],
        ['papua new guinea', Api.CountryType.PAPUA_NEW_GUINEA],
        ['philippines', Api.CountryType.PHILIPPINES],
        ['pitcairn island', Api.CountryType.PITCAIRN_ISLAND],
        ['samoa', Api.CountryType.SAMOA],
        ['singapore', Api.CountryType.SINGAPORE],
        ['solomon islands', Api.CountryType.SOLOMON_ISLANDS],
        ['south korea', Api.CountryType.SOUTH_KOREA],
        ['sri lanka', Api.CountryType.SRI_LANKA],
        ['taiwan', Api.CountryType.TAIWAN],
        ['tajikistan', Api.CountryType.TAJIKISTAN],
        ['thailand', Api.CountryType.THAILAND],
        ['timor leste', Api.CountryType.TIMOR_LESTE],
        ['tokelau', Api.CountryType.TOKELAU],
        ['tonga', Api.CountryType.TONGA],
        ['tuvalu', Api.CountryType.TUVALU],
        ['vanuatu', Api.CountryType.VANUATU],
        ['vietnam', Api.CountryType.VIETNAM],
        ['wallis and futuna', Api.CountryType.WALLIS_AND_FUTUNA],

        // Europe
        ['albania', Api.CountryType.ALBANIA],
        ['andorra', Api.CountryType.ANDORRA],
        ['armenia', Api.CountryType.ARMENIA],
        ['austria', Api.CountryType.AUSTRIA],
        ['azerbaijan', Api.CountryType.AZERBAIJAN],
        ['belarus', Api.CountryType.BELARUS],
        ['belgium', Api.CountryType.BELGIUM],
        ['bosnia and herzegovina', Api.CountryType.BOSNIA_AND_HERZEGOVINA],
        ['bulgaria', Api.CountryType.BULGARIA],
        ['croatia', Api.CountryType.CROATIA],
        ['cyprus', Api.CountryType.CYPRUS],
        ['czech republic', Api.CountryType.CZECH_REPUBLIC],
        ['denmark', Api.CountryType.DENMARK],
        ['estonia', Api.CountryType.ESTONIA],
        ['finland', Api.CountryType.FINLAND],
        ['france', Api.CountryType.FRANCE],
        ['georgia', Api.CountryType.GEORGIA],
        ['germany', Api.CountryType.GERMANY],
        ['gibraltar', Api.CountryType.GIBRALTAR],
        ['greece', Api.CountryType.GREECE],
        ['hungary', Api.CountryType.HUNGARY],
        ['iceland', Api.CountryType.ICELAND],
        ['ireland', Api.CountryType.IRELAND],
        ['italy', Api.CountryType.ITALY],
        ['kosovo', Api.CountryType.KOSOVO],
        ['latvia', Api.CountryType.LATVIA],
        ['liechtenstein', Api.CountryType.LIECHTENSTEIN],
        ['lithuania', Api.CountryType.LITHUANIA],
        ['luxembourg', Api.CountryType.LUXEMBOURG],
        ['malta', Api.CountryType.MALTA],
        ['moldova', Api.CountryType.MOLDOVA],
        ['monaco', Api.CountryType.MONACO],
        ['montenegro', Api.CountryType.MONTENEGRO],
        ['netherlands', Api.CountryType.NETHERLANDS],
        ['north macedonia', Api.CountryType.NORTH_MACEDONIA],
        ['norway', Api.CountryType.NORWAY],
        ['poland', Api.CountryType.POLAND],
        ['portugal', Api.CountryType.PORTUGAL],
        ['romania', Api.CountryType.ROMANIA],
        ['russia', Api.CountryType.RUSSIA],
        ['san marino', Api.CountryType.SAN_MARINO],
        ['serbia', Api.CountryType.SERBIA],
        ['slovakia', Api.CountryType.SLOVAKIA],
        ['slovenia', Api.CountryType.SLOVENIA],
        ['spain', Api.CountryType.SPAIN],
        ['sweden', Api.CountryType.SWEDEN],
        ['switzerland', Api.CountryType.SWITZERLAND],
        ['turkey', Api.CountryType.TURKEY],
        ['ukraine', Api.CountryType.UKRAINE],
        ['united kingdom', Api.CountryType.UNITED_KINGDOM],

        // Middle East & Africa
        ['afghanistan', Api.CountryType.AFGHANISTAN],
        ['algeria', Api.CountryType.ALGERIA],
        ['angola', Api.CountryType.ANGOLA],
        ['bahrain', Api.CountryType.BAHRAIN],
        ['benin', Api.CountryType.BENIN],
        ['botswana', Api.CountryType.BOTSWANA],
        ['burkina faso', Api.CountryType.BURKINA_FASO],
        ['burundi', Api.CountryType.BURUNDI],
        ['cape verde', Api.CountryType.CAPE_VERDE],
        ['cameroon', Api.CountryType.CAMEROON],
        ['central african republic', Api.CountryType.CENTRAL_AFRICAN_REPUBLIC],
        ['chad', Api.CountryType.CHAD],
        ['comoros', Api.CountryType.COMOROS],
        ['democratic republic of congo', Api.CountryType.DEMOCRATIC_REPUBLIC_OF_CONGO],
        ['republic of congo', Api.CountryType.REPUBLIC_OF_CONGO],
        ['djibouti', Api.CountryType.DJIBOUTI],
        ['egypt', Api.CountryType.EGYPT],
        ['equatorial guinea', Api.CountryType.EQUATORIAL_GUINEA],
        ['eritrea', Api.CountryType.ERITREA],
        ['eswatini', Api.CountryType.ESWATINI],
        ['ethiopia', Api.CountryType.ETHIOPIA],
        ['gabon', Api.CountryType.GABON],
        ['gambia', Api.CountryType.GAMBIA],
        ['ghana', Api.CountryType.GHANA],
        ['guinea', Api.CountryType.GUINEA],
        ['guinea bissau', Api.CountryType.GUINEA_BISSAU],
        ['iran', Api.CountryType.IRAN],
        ['iraq', Api.CountryType.IRAQ],
        ['israel', Api.CountryType.ISRAEL],
        ['jordan', Api.CountryType.JORDAN],
        ['kenya', Api.CountryType.KENYA],
        ['kuwait', Api.CountryType.KUWAIT],
        ['lebanon', Api.CountryType.LEBANON],
        ['lesotho', Api.CountryType.LESOTHO],
        ['liberia', Api.CountryType.LIBERIA],
        ['libya', Api.CountryType.LIBYA],
        ['madagascar', Api.CountryType.MADAGASCAR],
        ['malawi', Api.CountryType.MALAWI],
        ['mali', Api.CountryType.MALI],
        ['mauritania', Api.CountryType.MAURITANIA],
        ['mauritius', Api.CountryType.MAURITIUS],
        ['morocco', Api.CountryType.MOROCCO],
        ['mozambique', Api.CountryType.MOZAMBIQUE],
        ['namibia', Api.CountryType.NAMIBIA],
        ['niger', Api.CountryType.NIGER],
        ['nigeria', Api.CountryType.NIGERIA],
        ['oman', Api.CountryType.OMAN],
        ['pakistan', Api.CountryType.PAKISTAN],
        ['palestine', Api.CountryType.PALESTINE],
        ['qatar', Api.CountryType.QATAR],
        ['rwanda', Api.CountryType.RWANDA],
        ['sao tome and principe', Api.CountryType.SAO_TOME_AND_PRINCIPE],
        ['saudi arabia', Api.CountryType.SAUDI_ARABIA],
        ['senegal', Api.CountryType.SENEGAL],
        ['seychelles', Api.CountryType.SEYCHELLES],
        ['sierra leone', Api.CountryType.SIERRA_LEONE],
        ['somalia', Api.CountryType.SOMALIA],
        ['south africa', Api.CountryType.SOUTH_AFRICA],
        ['south sudan', Api.CountryType.SOUTH_SUDAN],
        ['sudan', Api.CountryType.SUDAN],
        ['syria', Api.CountryType.SYRIA],
        ['tanzania', Api.CountryType.TANZANIA],
        ['togo', Api.CountryType.TOGO],
        ['tunisia', Api.CountryType.TUNISIA],
        ['uganda', Api.CountryType.UGANDA],
        ['united arab emirates', Api.CountryType.UNITED_ARAB_EMIRATES],
        ['yemen', Api.CountryType.YEMEN],
        ['zambia', Api.CountryType.ZAMBIA],
        ['zimbabwe', Api.CountryType.ZIMBABWE],
    ])

    // Convert input to lowercase to match the map keys
    const formattedName = name.toLowerCase()

    return countryMap.get(formattedName) || Api.CountryType.WORLDWIDE
}
