import { Api } from '@/models/api'

export function getRegionByCountryCode(code: Api.CountryType): Api.RegionType {
    switch (code) {
        // Americas
        case Api.CountryType.ARGENTINA:
        case Api.CountryType.BAHAMAS:
        case Api.CountryType.BARBADOS:
        case Api.CountryType.BELIZE:
        case Api.CountryType.BERMUDA:
        case Api.CountryType.BOLIVIA:
        case Api.CountryType.BRAZIL:
        case Api.CountryType.CANADA:
        case Api.CountryType.CAYMAN_ISLANDS:
        case Api.CountryType.CHILE:
        case Api.CountryType.COLOMBIA:
        case Api.CountryType.COSTA_RICA:
        case Api.CountryType.CUBA:
        case Api.CountryType.DOMINICA:
        case Api.CountryType.DOMINICAN_REPUBLIC:
        case Api.CountryType.ECUADOR:
        case Api.CountryType.EL_SALVADOR:
        case Api.CountryType.FALKLAND_ISLANDS:
        case Api.CountryType.GRENADA:
        case Api.CountryType.GREENLAND:
        case Api.CountryType.GUATEMALA:
        case Api.CountryType.GUYANA:
        case Api.CountryType.HAITI:
        case Api.CountryType.HONDURAS:
        case Api.CountryType.JAMAICA:
        case Api.CountryType.MEXICO:
        case Api.CountryType.NICARAGUA:
        case Api.CountryType.PANAMA:
        case Api.CountryType.PARAGUAY:
        case Api.CountryType.PERU:
        case Api.CountryType.PUERTO_RICO:
        case Api.CountryType.SAINT_KITTS_AND_NEVIS:
        case Api.CountryType.SAINT_LUCIA:
        case Api.CountryType.SAINT_VINCENT_AND_THE_GRENADINES:
        case Api.CountryType.SURINAME:
        case Api.CountryType.TRINIDAD_AND_TOBAGO:
        case Api.CountryType.UNITED_STATES:
        case Api.CountryType.URUGUAY:
        case Api.CountryType.VENEZUELA:
        case Api.CountryType.VIRGIN_ISLANDS_BRITISH:
        case Api.CountryType.VIRGIN_ISLANDS_US:
            return Api.RegionType.AMERICAS

        // Asia Pacific
        case Api.CountryType.AUSTRALIA:
        case Api.CountryType.BANGLADESH:
        case Api.CountryType.BHUTAN:
        case Api.CountryType.BRUNEI_DARUSSALAM:
        case Api.CountryType.CAMBODIA:
        case Api.CountryType.CHINA:
        case Api.CountryType.CHRISTMAS_ISLAND:
        case Api.CountryType.COCOS_ISLANDS:
        case Api.CountryType.FIJI:
        case Api.CountryType.HONG_KONG:
        case Api.CountryType.INDIA:
        case Api.CountryType.INDONESIA:
        case Api.CountryType.JAPAN:
        case Api.CountryType.KAZAKHSTAN:
        case Api.CountryType.KIRIBATI:
        case Api.CountryType.LAOS:
        case Api.CountryType.MACAU:
        case Api.CountryType.MALAYSIA:
        case Api.CountryType.MALDIVES:
        case Api.CountryType.MARSHALL_ISLANDS:
        case Api.CountryType.MICRONESIA:
        case Api.CountryType.MONGOLIA:
        case Api.CountryType.MYANMAR:
        case Api.CountryType.NEPAL:
        case Api.CountryType.NEW_CALEDONIA:
        case Api.CountryType.NEW_ZEALAND:
        case Api.CountryType.NIUE:
        case Api.CountryType.NORTH_KOREA:
        case Api.CountryType.NORTHERN_MARIANA_ISLANDS:
        case Api.CountryType.PALAU:
        case Api.CountryType.PAPUA_NEW_GUINEA:
        case Api.CountryType.PHILIPPINES:
        case Api.CountryType.PITCAIRN_ISLAND:
        case Api.CountryType.SAMOA:
        case Api.CountryType.SINGAPORE:
        case Api.CountryType.SOLOMON_ISLANDS:
        case Api.CountryType.SOUTH_KOREA:
        case Api.CountryType.SRI_LANKA:
        case Api.CountryType.TAIWAN:
        case Api.CountryType.TAJIKISTAN:
        case Api.CountryType.THAILAND:
        case Api.CountryType.TIMOR_LESTE:
        case Api.CountryType.TOKELAU:
        case Api.CountryType.TONGA:
        case Api.CountryType.TUVALU:
        case Api.CountryType.VANUATU:
        case Api.CountryType.VIETNAM:
        case Api.CountryType.WALLIS_AND_FUTUNA:
            return Api.RegionType.ASIA_PACIFIC

        // Europe
        case Api.CountryType.ALBANIA:
        case Api.CountryType.ANDORRA:
        case Api.CountryType.ARMENIA:
        case Api.CountryType.AUSTRIA:
        case Api.CountryType.AZERBAIJAN:
        case Api.CountryType.BELARUS:
        case Api.CountryType.BELGIUM:
        case Api.CountryType.BOSNIA_AND_HERZEGOVINA:
        case Api.CountryType.BULGARIA:
        case Api.CountryType.CROATIA:
        case Api.CountryType.CYPRUS:
        case Api.CountryType.CZECH_REPUBLIC:
        case Api.CountryType.DENMARK:
        case Api.CountryType.ESTONIA:
        case Api.CountryType.FINLAND:
        case Api.CountryType.FRANCE:
        case Api.CountryType.GEORGIA:
        case Api.CountryType.GERMANY:
        case Api.CountryType.GIBRALTAR:
        case Api.CountryType.GREECE:
        case Api.CountryType.HUNGARY:
        case Api.CountryType.ICELAND:
        case Api.CountryType.IRELAND:
        case Api.CountryType.ITALY:
        case Api.CountryType.KOSOVO:
        case Api.CountryType.LATVIA:
        case Api.CountryType.LIECHTENSTEIN:
        case Api.CountryType.LITHUANIA:
        case Api.CountryType.LUXEMBOURG:
        case Api.CountryType.MALTA:
        case Api.CountryType.MOLDOVA:
        case Api.CountryType.MONACO:
        case Api.CountryType.MONTENEGRO:
        case Api.CountryType.NETHERLANDS:
        case Api.CountryType.NORTH_MACEDONIA:
        case Api.CountryType.NORWAY:
        case Api.CountryType.POLAND:
        case Api.CountryType.PORTUGAL:
        case Api.CountryType.ROMANIA:
        case Api.CountryType.RUSSIA:
        case Api.CountryType.SAN_MARINO:
        case Api.CountryType.SERBIA:
        case Api.CountryType.SLOVAKIA:
        case Api.CountryType.SLOVENIA:
        case Api.CountryType.SPAIN:
        case Api.CountryType.SWEDEN:
        case Api.CountryType.SWITZERLAND:
        case Api.CountryType.TURKEY:
        case Api.CountryType.UKRAINE:
        case Api.CountryType.UNITED_KINGDOM:
            return Api.RegionType.EUROPE

        // Middle East and Africa
        case Api.CountryType.AFGHANISTAN:
        case Api.CountryType.ALGERIA:
        case Api.CountryType.ANGOLA:
        case Api.CountryType.BAHRAIN:
        case Api.CountryType.BENIN:
        case Api.CountryType.BOTSWANA:
        case Api.CountryType.BURKINA_FASO:
        case Api.CountryType.BURUNDI:
        case Api.CountryType.CAPE_VERDE:
        case Api.CountryType.CAMEROON:
        case Api.CountryType.CENTRAL_AFRICAN_REPUBLIC:
        case Api.CountryType.CHAD:
        case Api.CountryType.COMOROS:
        case Api.CountryType.DEMOCRATIC_REPUBLIC_OF_CONGO:
        case Api.CountryType.REPUBLIC_OF_CONGO:
        case Api.CountryType.DJIBOUTI:
        case Api.CountryType.EGYPT:
        case Api.CountryType.EQUATORIAL_GUINEA:
        case Api.CountryType.ERITREA:
        case Api.CountryType.ESWATINI:
        case Api.CountryType.ETHIOPIA:
        case Api.CountryType.GABON:
        case Api.CountryType.GAMBIA:
        case Api.CountryType.GHANA:
        case Api.CountryType.GUINEA:
        case Api.CountryType.GUINEA_BISSAU:
        case Api.CountryType.IRAN:
        case Api.CountryType.IRAQ:
        case Api.CountryType.ISRAEL:
        case Api.CountryType.JORDAN:
        case Api.CountryType.KENYA:
        case Api.CountryType.KUWAIT:
        case Api.CountryType.LEBANON:
        case Api.CountryType.LESOTHO:
        case Api.CountryType.LIBERIA:
        case Api.CountryType.LIBYA:
        case Api.CountryType.MADAGASCAR:
        case Api.CountryType.MALAWI:
        case Api.CountryType.MALI:
        case Api.CountryType.MAURITANIA:
        case Api.CountryType.MAURITIUS:
        case Api.CountryType.MOROCCO:
        case Api.CountryType.MOZAMBIQUE:
        case Api.CountryType.NAMIBIA:
        case Api.CountryType.NIGER:
        case Api.CountryType.NIGERIA:
        case Api.CountryType.OMAN:
        case Api.CountryType.PAKISTAN:
        case Api.CountryType.PALESTINE:
        case Api.CountryType.QATAR:
        case Api.CountryType.RWANDA:
        case Api.CountryType.SAO_TOME_AND_PRINCIPE:
        case Api.CountryType.SAUDI_ARABIA:
        case Api.CountryType.SENEGAL:
        case Api.CountryType.SEYCHELLES:
        case Api.CountryType.SIERRA_LEONE:
        case Api.CountryType.SOMALIA:
        case Api.CountryType.SOUTH_AFRICA:
        case Api.CountryType.SOUTH_SUDAN:
        case Api.CountryType.SUDAN:
        case Api.CountryType.SYRIA:
        case Api.CountryType.TANZANIA:
        case Api.CountryType.TOGO:
        case Api.CountryType.TUNISIA:
        case Api.CountryType.UGANDA:
        case Api.CountryType.UNITED_ARAB_EMIRATES:
        case Api.CountryType.YEMEN:
        case Api.CountryType.ZAMBIA:
        case Api.CountryType.ZIMBABWE:
            return Api.RegionType.MIDDLE_EAST_AFRICA

        // WorldWide Fallback
        default:
            return Api.RegionType.WORLDWIDE
    }
}
