export const AuthenticationEvent = {
    FORGOT_PASSWORD_RESET: 'FORGOT_PASSWORD_RESET',
    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REFRESH: 'REFRESH',
    RESEND_EMAIL_VERIFICATION: 'RESEND_EMAIL_VERIFICATION',
    SIGNUP_WITH_EMAIL: 'SIGNUP_WITH_EMAIL',
    VERIFIED_EMAIL_CODE: 'VERIFIED_EMAIL_CODE',
    VERIFIED_EMAIL_LINK: 'VERIFIED_EMAIL_LINK',
} as const
